### ISSUE TITLE
下载不了呢？

### ISSUE THREAD

**Issue by xinxingzhao** [yohnz/weather#1]
点进去是404

**Comment by xinxingzhao** [comment]
需要点击
![selection_008](https://cloud.githubusercontent.com/assets/13712791/15352423/b08fb828-1d16-11e6-934e-245e698f5e3a.png)
这个文件下载

但是安装出了问题
![selection_009](https://cloud.githubusercontent.com/assets/13712791/15352437/c25cadfe-1d16-11e6-8a9a-8150404c16d7.png)

**Comment by yohnz** [comment]
@xinxingzhao 嗯mac上直接安装有问题，你可以打开chrome扩展程序界面(chrome地址栏输入`chrome://extensions/`),然后拖拽weather文件夹进去。
![1](https://cloud.githubusercontent.com/assets/6244526/15415443/521704bc-1e75-11e6-9c74-07a84954a29c.png)

**Comment by xinxingzhao** [comment]
我的是Ubuntu，也是直接拖拽进去的，应该是别的问题引起的。

**Comment by yohnz** [comment]
@xinxingzhao 拖文件夹，别拖crx文件试试

**Comment by xinxingzhao** [comment]
Failed to load extension from: ~/code/weather
Manifest file is missing or unreadable.

报了这个错误。

**Comment by yohnz** [comment]
@xinxingzhao 你看下weather文件夹里有没有manifest.json，没有的话git pull一下

**Comment by xinxingzhao** [comment]
@yohnz  有的，我刚刚clone下来的代码，应该是最新的代码。

**Comment by yohnz** [comment]
@xinxingzhao 等我有空了装个ubuntu瞧瞧
